"""Freeze every expensive clipper artifact to disk, and inventory what exists.

Why this exists: a transcript costs ~30 minutes of GPU for a 4-hour source and
lives only in SQLite, so a lost or reset database throws away hours. A proxy
costs a full ffmpeg pass over the source. Neither is reproducible for free, and
both are needed again by every re-run and every experiment.

What it does, both idempotent and safe to re-run at any time:

  1. Writes each project's transcript to `<project>/analysis/transcript.json`,
     next to the artifacts that were derived from it.
  2. Writes `data/clipper/MANIFEST.md` — one row per project, saying which
     stages are already on disk, so the next session can tell at a glance what
     it can skip.

Run it again after any stage finishes; it only rewrites what changed.

    PYTHONPATH=<repo>/server python scripts/export_clipper_state.py
"""

from __future__ import annotations

import json
import os
import sqlite3
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_SERVER = _HERE.parent / "server"
if str(_SERVER) not in sys.path:
    sys.path.insert(0, str(_SERVER))

DATA = Path(os.environ.get("CLIPFORGE_DATA_DIR") or (_HERE.parent / "data"))
CLIPPER = DATA / "clipper"
DB = DATA / "db" / "clipforge.db"

# Stage -> the file that proves it finished. Order is pipeline order, so the
# manifest reads left to right as progress.
STAGE_FILES = [
    ("source", "source"),                       # directory, any video inside
    ("proxy", "proxy/proxy.mp4"),
    ("audio", "audio/speech.wav"),
    ("transcript", "analysis/transcript.json"),
    ("signals", "analysis/signals.json"),
    ("regions", "analysis/regions.json"),
    ("atoms", "analysis/atoms.json"),
    ("candidates", "analysis/candidates.json"),
]


def _mb(n: float) -> str:
    return f"{n / 1024 / 1024:,.0f} MB" if n else "—"


def _dir_bytes(d: Path) -> int:
    if not d.is_dir():
        return 0
    return sum(f.stat().st_size for f in d.rglob("*") if f.is_file())


def _present(root: Path, rel: str) -> tuple[bool, int]:
    p = root / rel
    if p.is_dir():
        size = _dir_bytes(p)
        return size > 0, size
    if p.is_file():
        return True, p.stat().st_size
    return False, 0


def export_transcripts(db: sqlite3.Connection) -> list[str]:
    """Write every transcript beside its project. Returns what was written."""
    written = []
    rows = db.execute(
        "select project_id, language, segments, full_text, word_count "
        "from transcripts"
    ).fetchall()
    for row in rows:
        pid = row["project_id"]
        root = CLIPPER / pid
        if not root.is_dir():
            continue  # a non-clipper project, or one already cleaned up
        out = root / "analysis" / "transcript.json"
        payload = {
            "project_id": pid,
            "language": row["language"],
            "word_count": row["word_count"],
            "full_text": row["full_text"],
            "segments": json.loads(row["segments"]) if row["segments"] else [],
        }
        body = json.dumps(payload, ensure_ascii=False)
        if out.exists() and out.read_text(encoding="utf-8") == body:
            continue  # unchanged; do not churn the file
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8")
        written.append(pid)
    return written


def build_manifest(db: sqlite3.Connection) -> str:
    # Driven by the DIRECTORIES, not by a `processing_mode` filter: the whole
    # point of the manifest is what is on disk, and projects created by hand in
    # earlier sessions have processing_mode NULL. Filtering on it silently hid
    # slice4h00test — 908 clips and every artifact, the most valuable project
    # here.
    on_disk = sorted(
        (d for d in CLIPPER.iterdir() if d.is_dir() and not d.name.startswith("_")),
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )
    rows = []
    for d in on_disk:
        row = db.execute(
            "select id, title, status, duration, source_url, content_type "
            "from projects where id = ?", (d.name,)
        ).fetchone()
        rows.append(row if row else {"id": d.name, "title": "(not in the database)",
                                     "status": "orphan", "duration": 0})

    lines = [
        "# Clipper projects on this machine",
        "",
        "Generated by `scripts/export_clipper_state.py`. Every ✓ is work that "
        "does NOT need doing again — a proxy is a full ffmpeg pass, a "
        "transcript is GPU minutes proportional to the source.",
        "",
        "| project | source | dur | status | "
        + " | ".join(name for name, _ in STAGE_FILES)
        + " | on disk |",
        "|---|---|---|---|" + "---|" * (len(STAGE_FILES) + 1),
    ]

    total = 0
    for row in rows:
        pid = row["id"]
        root = CLIPPER / pid
        marks = []
        for _name, rel in STAGE_FILES:
            ok, _size = _present(root, rel)
            marks.append("✓" if ok else "·")
        size = _dir_bytes(root)
        total += size
        dur = float(row["duration"] or 0)
        title = (row["title"] or "").replace("|", "/")[:46]
        lines.append(
            f"| `{pid}` | {title} | {dur / 60:.0f}m | {row['status']} | "
            + " | ".join(marks)
            + f" | {_mb(size)} |"
        )

    lines += [
        "",
        f"**Total on disk: {_mb(total)}**",
        "",
        "## Reusing this",
        "",
        "- A project with ✓ through `audio` can go straight to transcription.",
        "- A project with ✓ on `transcript` never needs the GPU again: the JSON "
        "beside it carries the segments with word-level timings, so it can be "
        "loaded back into SQLite if the database is ever lost.",
        "- `data/clipper/_uploads/batch/` holds the downloaded originals. They "
        "are copied into each project, so the batch copies are only needed to "
        "re-create a project from scratch.",
        "- Downloads need cookies and a JS runtime — see "
        "`CLIPFORGE_YTDLP_COOKIES_FILE` and `CLIPFORGE_YTDLP_JS_RUNTIMES` in "
        "`server/config.py`. YouTube rotates cookies, so an export is usually "
        "good for one session.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if not DB.exists():
        raise SystemExit(f"no database at {DB}")
    db = sqlite3.connect(DB)
    db.row_factory = sqlite3.Row

    written = export_transcripts(db)
    print(f"transcripts written: {len(written)}"
          + (f" ({', '.join(written)})" if written else " (all current)"))

    manifest = build_manifest(db)
    out = CLIPPER / "MANIFEST.md"
    out.write_text(manifest, encoding="utf-8")
    # Deliberately not echoed: the table uses ✓, and a Windows console on
    # cp1252 raises UnicodeEncodeError on it. The file is UTF-8 and fine.
    rows = sum(1 for line in manifest.splitlines() if line.startswith("| `"))
    print(f"manifest: {out} ({rows} projects)")


if __name__ == "__main__":
    main()
